### ISSUE TITLE
指摘箇所の修正と図の変更

### ISSUE THREAD

**Issue by Komatsu1932047** [Komatsu1932047/kougai_saisyu#5]
指摘された箇所を修正
3章で，図1を削除，参照していた文を削除
4章で，シミュレータ画面の図2を追加，4章終わりに説明の文を追加

**Comment by sudahiroshi** [comment]
issueは作業報告ではなく，不具合とその対応の報告です．
今後はそのように使ってください．

上記項目はすべてクリアされているので，closeしておいてください．
